2025-08-31 00:54:47,191 - model_evaluation - ERROR - Failed to complete model evaluation: Failed to upload C:\Users\KIIT\AppData\Local\Temp\tmp5bj_zu5w\model\conda.yaml to mlflow-test-241103/932365010241693130/models/m-4aebfbf8321d4f518edc970447bda144/artifacts/conda.yaml: An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist
2025-08-31 00:55:53,233 - model_evaluation - ERROR - Failed to complete model evaluation: Failed to upload C:\Users\KIIT\AppData\Local\Temp\tmp67x9e0bn\model\conda.yaml to mlflow-test-241103/932365010241693130/models/m-895e8e484b5445de8f580b880d2d356c/artifacts/conda.yaml: An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist
2025-08-31 01:12:55,701 - model_evaluation - ERROR - Failed to complete model evaluation: Failed to upload C:\Users\KIIT\AppData\Local\Temp\tmpzdhxikw8\model\conda.yaml to mlflow-test-241103/932365010241693130/models/m-0d101de517744d42ba708dfba7be657a/artifacts/conda.yaml: An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist
2025-08-31 01:15:10,718 - model_evaluation - ERROR - Failed to complete model evaluation: Failed to upload C:\Users\KIIT\AppData\Local\Temp\tmpczodai9h\model\conda.yaml to mlflow-test-241103/932365010241693130/models/m-2e4012ae75864aaeaa5b10a9f61853ff/artifacts/conda.yaml: An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist
2025-08-31 01:15:52,121 - model_evaluation - ERROR - Failed to complete model evaluation: Failed to upload C:\Users\KIIT\AppData\Local\Temp\tmpmife2xfi\model\conda.yaml to mlflow-test-241103/932365010241693130/models/m-263132457e9c4c1e8ad38e9d599aa469/artifacts/conda.yaml: An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist
2025-08-31 01:17:45,351 - model_evaluation - ERROR - Failed to complete model evaluation: Failed to upload C:\Users\KIIT\AppData\Local\Temp\tmpqhyrwxpm\model\conda.yaml to mlflow-test-241103/932365010241693130/models/m-7f642395ddf74f838d7ec846927ef491/artifacts/conda.yaml: An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist
2025-08-31 01:20:56,258 - model_evaluation - ERROR - Failed to complete model evaluation: Failed to upload C:\Users\KIIT\AppData\Local\Temp\tmpfezeynp2\model\conda.yaml to mlflow-test-241103/932365010241693130/models/m-d4aa913b23be48c792e8a264df5db7c6/artifacts/conda.yaml: An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist
2025-08-31 01:26:57,818 - model_evaluation - ERROR - Failed to complete model evaluation: Failed to upload C:\Users\KIIT\AppData\Local\Temp\tmpa87wn7qf\model\conda.yaml to mlflow-test-241103/932365010241693130/models/m-b6ec1209ab754c46a1269f0fcade932c/artifacts/conda.yaml: An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist
